# -*- coding: utf-8 -*-

{
    'name': 'hr_novelty',
    'version': '12.0.1.0',
    'author': 'Destiny',
    'website': 'https://www.destiny.ws',
    'category': 'Human Resources',
    'summary': "Module to manage employee's novelties. i.e: ",
    'depends': ['base',
                'mail',
                'hr',
                'hr_payroll',
                'hr_holidays',
                'base_product',
                'hr_extended',
                'hr_curriculum_vitae',
                'recruitment_reason',
                'hr_recruitment_extended',
                'partner_product',
                'ir_attachment_s3',
                'hr_contract_extended'
                ],
    'data': [
        'security/hr_novelty_security.xml',
        'data/motivo_talento_data.xml',
        'data/calendar_data.xml',
        'data/hr_novelty_type.xml',
        'data/hr_novelty_type_subtype.xml',
        'data/hr_novelty_data.xml',
        'wizard/novelty_create_contact_view.xml',
        'wizard/novelty_create_employee_view.xml',
        'wizard/novelty_create_contract_view.xml',
        'views/hr_novelty_view.xml',
        'data/hr_novelty_event.xml',
        'views/hr_leave_view.xml',
        'views/hr_you_fields_view.xml',
        'views/hr_module_you_view.xml',
        'views/hr_you_type_view.xml',
        'views/motivo_talento_view.xml',
        'wizard/novelty_reject_wizard_view.xml',
        'views/hr_employee_view.xml',
        'data/ir.sequence.xml',
        'security/ir.model.access.csv',
        'security/ir.rule.xml',
        'views/inherited_hr_leaves_view.xml',
        'views/inherited_hr_payslip_view.xml',
        'views/hr_novelty_job_view.xml',
        'views/inherited_hr_job_view.xml',
        'views/hr_leave_code_view.xml',
        'views/inherited_hr_contract_view.xml',
        'views/res_partner_bank_view.xml',
    ],
    'installable': True,
    'application': False,
    'external_dependencies': {
        'python': ['ip2geotools'],
    }
}
