# -*- coding: utf-8 -*-

from . import hr_academic_area
from . import hr_cv_pets
from . import hr_cv_employee
from . import hr_category_hobbies
from . import hr_hobbies
from . import hr_cv_hobbies_employee
from . import hr_sports
from . import hr_cv_sports_employee
from . import hr_language
from . import hr_experience_time
from . import hr_cv_language_employee
from . import hr_holding
from . import hr_cv_holding_employee
from . import hr_family_relationship
from . import hr_occupations
from . import hr_cv_family_group_employee
from . import hr_experience_area
from . import hr_external_job_position
from . import hr_type_contract
from . import hr_cv_laboral_experience
from . import hr_academic_institution
from . import hr_academic_level
from . import hr_cv_academic_studies
from . import hr_competition_language
from . import hr_competition_level_language
from . import hr_cv_personal_employee_type
from . import hr_cv_personal_reference_employee
from . import tools_management
from . import hr_employee
from . import hr_family_group_categ
from . import ir_attachment
